test v3

diff --git a/.github/workflows/lockfileversion-check.yml b/.github/workflows/lockfileversion-check.yml
--- a/.github/workflows/lockfileversion-check.yml
+++ b/.github/workflows/lockfileversion-check.yml
@@ -11,20 +11,20 @@ on:
 
 jobs:
   version-check:
-    runs-on:  ubuntu-20.04
-    env:
-      VERSION: '0'
+    runs-on: ubuntu-20.04
+    outputs:
+      output1: ${{ steps.getversion.outputs.version }}
     steps:
-    - name: Checkout
-      uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Retrieve version
-      id: getversion
-      run: |
-        cat package-lock.json | grep '\"lockfileVersion\": 2,' > ${{ VERSION }};
-        echo "$VERSION";
-    - name: check value
-      if: ${{ env.VERSION == null }}
-      run: |
-        echo "ERROR: Outdated package-lock file. Use NPM8 to install dependencies ";
-        exit 1
+      - name: Retrieve version
+        id: getversion
+        run: |
+          echo "::set-output name=version::$(cat package-lock.json | grep '\"lockfileVersion\": 2,')"
+
+      - name: check value
+        if: ${{ steps.getversion.outputs.version == null }}
+        run: |
+          echo "ERROR: Outdated package-lock file. Use NPM9 to install dependencies "
+          exit 1
