test final

diff --git a/.github/workflows/lockfileversion-check.yml b/.github/workflows/lockfileversion-check.yml
--- a/.github/workflows/lockfileversion-check.yml
+++ b/.github/workflows/lockfileversion-check.yml
@@ -11,20 +11,18 @@ on:
 
 jobs:
   version-check:
-    runs-on: ubuntu-20.04
-    outputs:
-      output1: ${{ steps.getversion.outputs.version }}
+    runs-on:  ubuntu-20.04
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+    - name: Checkout
+      uses: actions/checkout@v2
 
-      - name: Retrieve version
-        id: getversion
-        run: |
-          echo "::set-output name=version::$(cat package-lock.json | grep '\"lockfileVersion\": 2,')"
-
-      - name: check value
-        if: ${{ steps.getversion.outputs.version == null }}
-        run: |
-          echo "ERROR: Outdated package-lock file. Use NPM9 to install dependencies "
-          exit 1
+    - name: Retrieve version
+      id: getversion
+      run: |
+        echo "VERSION=$(cat package-lock.json | grep '\"lockfileVersion\": 2,')" >> $GITHUB_ENV
+        echo "${{ env.VERSION }}";
+    - name: check value
+      if: ${{ env.VERSION == null }}
+      run: |
+        echo "ERROR: Outdated package-lock file. Use NPM8 to install dependencies ";
+        exit 1
